# Basic Python

## 1. Split this string

In [23]:
s = "Hi there Sam!"

In [24]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [25]:
planet = "Earth"
diameter = 12742

In [26]:
print("The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [27]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [28]:
print( d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [29]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [30]:
Arr=np.array([0,0,0,0,0,0,0,0,0,0])
Arr1=np.array([5,5,5,5,5,5,5,5,5,5])

In [31]:
print(Arr)
print(Arr1)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [32]:
Arr2=np.arange(20,35,2)
print(Arr2)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
Arr3=np.arange(0,9).reshape(3,3)
print(Arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr = np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [35]:
import pandas as pd

In [36]:
df={
    "Name":['a','b','c'],
    "Marks":[10,20,30]
}

In [37]:
dataframe = pd.DataFrame(df)
print(dataframe)

  Name  Marks
0    a     10
1    b     20
2    c     30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [38]:
d=pd.date_range(start='1/1/2023', end='10/02/2023')

In [39]:
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [43]:
df = pd.DataFrame(lists, columns =['F_No', 'Name', 'L_No'],
                                           dtype = int) 
print(df)

   F_No Name  L_No
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24


C:\Users\preetha sheeba\AppData\Local\Temp\ipykernel_10592\2811539885.py:1: FutureWarning: Could not cast to int32, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df = pd.DataFrame(lists, columns =['F_No', 'Name', 'L_No'],
